version: 2

sources:
  - name: eloise-challenge-1-sql
    schema: meteorological_hazards_project
    tables: 
      - name: 2000_2024_disasters
      - name: cities
      - name: animation_map_clean
      - name: global_deaths_geo_en_cities
      - name: magnitude
      - name: magnitude_new
      - name: magnitude_final
      - name: coordinates_cities_countries

        